name: update 

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install all necessary packages
      run: pip install jupyter lxml pandas requests regex numpy dotenv
    - name: Scraping today's data
      run: jupyter nbconvert --to notebook --execute "cpi-scraper.ipynb" --stdout
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
